{{/*
Copyright 2026 The Butler Authors.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if and .Values.server.enabled .Values.server.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "butler-console.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "butler-console.server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.server.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "butler-console.server.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "butler-console.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "butler-console.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "butler-console.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
