apiVersion: v2
name: butler-provider-nutanix
description: Butler infrastructure provider for Nutanix AHV
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0-0"

keywords:
  - butler
  - kubernetes
  - nutanix
  - hci
  - infrastructure

home: https://butlerlabs.dev
sources:
  - https://github.com/butlerdotdev/butler-provider-nutanix
  - https://github.com/butlerdotdev/butler-charts

maintainers:
  - name: Butler Labs
    email: founder@butlerlabs.dev
    url: https://butlerlabs.dev

annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/prerelease: "true"
