apiVersion: v2
name: butler-crds
description: Butler Custom Resource Definitions for Kubernetes-native multi-cluster management
type: application
version: 0.1.0
appVersion: "v1alpha1"
kubeVersion: ">=1.28.0-0"

keywords:
  - butler
  - kubernetes
  - multi-cluster
  - crds
  - platform

home: https://butlerlabs.dev
sources:
  - https://github.com/butlerdotdev/butler-api
  - https://github.com/butlerdotdev/butler-charts

maintainers:
  - name: Butler Labs
    email: founder@butlerlabs.dev
    url: https://butlerlabs.dev

annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
  artifacthub.io/signKey: |
    fingerprint: ""
    url: ""
